import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Gamepad2,Search,User,Heart,Play,Star,Menu,X,Flame,Target,Gift,ArrowLeft,RotateCcw, Trophy, Zap} from 'lucide-react';
import './styles.css';

type Game={id:number;title:string;category:string;rating:number;plays:string;icon:string;gradient:string;description?:string};
const games:Game[]=[
{id:1,title:'Neon Blocks',category:'Puzzle',rating:4.9,plays:'12.4K',icon:'◈',gradient:'g1'},
{id:2,title:'Space Rush',category:'Arcade',rating:4.8,plays:'9.8K',icon:'✦',gradient:'g2'},
{id:3,title:'Card Masters',category:'Cartas',rating:4.7,plays:'8.1K',icon:'♠',gradient:'g3'},
{id:4,title:'Goal Master',category:'Esportes',rating:4.9,plays:'7.6K',icon:'⚽',gradient:'g4'},
{id:5,title:'Candy Match',category:'Casual',rating:4.8,plays:'15.2K',icon:'◆',gradient:'g5'},
{id:6,title:'Tower Quest',category:'Estratégia',rating:4.6,plays:'6.3K',icon:'♜',gradient:'g6'},
{id:7,title:'Sky Flight',category:'Arcade',rating:4.9,plays:'18.7K',icon:'✈',gradient:'g7',description:'Desvie dos obstáculos e mantenha o voo pelo maior tempo possível.'},
{id:8,title:'Tiger Quest',category:'Casual',rating:4.8,plays:'16.1K',icon:'🐯',gradient:'g8',description:'Colete estrelas e evite os obstáculos da selva.'},
{id:9,title:'Hoops Challenge',category:'Esportes',rating:4.9,plays:'21.3K',icon:'🏀',gradient:'g9',description:'Acerte o maior número de arremessos no tempo disponível.'},
{id:10,title:'Card Duel',category:'Cartas',rating:4.7,plays:'5.9K',icon:'🃑',gradient:'g10',description:'Adivinhe se a próxima carta é maior ou menor e mantenha a sequência.'},
{id:11,title:'Poker Jacks or Better',category:'Cartas',rating:4.9,plays:'11.2K',icon:'🂡',gradient:'g11',description:'Segure as cartas certas, compre e monte a melhor mão possível.'}
];

function Header({onHome}:{onHome?:()=>void}){const[menu,setMenu]=useState(false);return <><header><button className="brand" onClick={onHome}><span className="brandMark"><Gamepad2/></span><span>PLAY<span>HUB</span></span></button><nav><button className="active" onClick={onHome}>Início</button><button>Jogos</button><button>Ranking</button><button>Conquistas</button></nav><div className="headerRight"><div className="search"><Search size={18}/><input placeholder="Buscar jogos..."/></div><button className="profile"><User size={19}/><span>Meu perfil</span></button><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>{menu&&<div className="mobileMenu">{['Início','Jogos','Ranking','Conquistas','Meu perfil'].map(x=><button key={x}>{x}</button>)}</div>}</>}

function App(){const[cat,setCat]=useState('Todos');const[q,setQ]=useState('');const[favorites,setFavorites]=useState<number[]>([]);const[selected,setSelected]=useState<Game|null>(null);const filtered=games.filter(g=>(cat==='Todos'||g.category===cat)&&g.title.toLowerCase().includes(q.toLowerCase()));const toggle=(id:number)=>setFavorites(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id]);if(selected)return <GamePage game={selected} back={()=>setSelected(null)}/>;return <div className="app"><Header/><main><section className="hero"><div className="heroText"><div className="eyebrow"><Flame size={15}/> EM ALTA AGORA</div><h1>Jogue. Evolua.<br/><em>Divirta-se.</em></h1><p>Jogos gratuitos, desafios e recordes pessoais. Comece uma partida em segundos.</p><button className="primary" onClick={()=>setSelected(games[6])}><Play size={18} fill="currentColor"/> Jogar Sky Flight</button></div><div className="heroArt"><div className="orb">✈</div><div className="floatCard fc1">🏆 <b>+250 XP</b></div><div className="floatCard fc2">🔥 <b>12 dias</b></div></div></section><section className="stats"><div><b>27</b><span>Jogos disponíveis</span></div><div><b>8.4K</b><span>Jogadores ativos</span></div><div><b>156K</b><span>Partidas realizadas</span></div><div><b>4.8</b><span>Avaliação média</span></div></section><div className="sectionHead"><div><h2>Explore os jogos</h2><p>Escolha uma categoria e comece a jogar.</p></div><div className="inlineSearch"><Search size={16}/><input placeholder="Buscar" value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="cats">{['Todos','Arcade','Puzzle','Estratégia','Cartas','Esportes','Casual'].map(c=><button className={cat===c?'selected':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="grid">{filtered.map(g=><article className="gameCard" key={g.id} onClick={()=>setSelected(g)}><div className={'cover '+g.gradient}><span className="gameIcon">{g.icon}</span><button className="heart" onClick={e=>{e.stopPropagation();toggle(g.id)}}>{favorites.includes(g.id)?<Heart fill="currentColor"/>:<Heart/>}</button><span className="play"><Play size={17} fill="currentColor"/></span></div><div className="gameInfo"><div><h3>{g.title}</h3><span>{g.category}</span></div><div className="rating"><Star size={14} fill="currentColor"/>{g.rating}</div></div><div className="plays">{g.plays} jogadores</div></article>)}</div><section className="challenge"><div><div className="eyebrow"><Target size={15}/> DESAFIO DIÁRIO</div><h2>Complete 3 partidas hoje</h2><p>Ganhe <b>+100 XP</b> e desbloqueie uma nova conquista.</p><div className="progress"><span style={{width:'66%'}}/></div><small>2 de 3 concluídas</small></div><Gift size={80} className="gift"/></section></main><footer><span>© 2026 PlayHub</span><span>Jogos gratuitos • Sem apostas • Sem dinheiro real</span></footer></div>}

function GamePage({game,back}:{game:Game;back:()=>void}){return <div className="app"><Header onHome={back}/><main className="gamePage"><button className="back" onClick={back}><ArrowLeft size={16}/> Voltar aos jogos</button><div className={'gameStage '+game.gradient}>{game.id===7?<SkyFlight/>:game.id===8?<TigerQuest/>:game.id===9?<Hoops/>:game.id===3?<CardMasters/>:game.id===10?<CardDuel/>:game.id===11?<PokerDraw/>:<DemoGame game={game}/>}</div></main></div>}

function ScoreBar({score,best,onRestart,playing}:{score:number;best:number;onRestart:()=>void;playing:boolean}){return <div className="scoreBar"><div><span>PONTOS</span><b>{score}</b></div><div><span>RECORDE</span><b>{best}</b></div>{!playing&&<button className="restart" onClick={onRestart}><RotateCcw size={16}/> Jogar novamente</button>}</div>}
function SkyFlight(){const[playing,setPlaying]=useState(true),[score,setScore]=useState(0),[best,setBest]=useState(()=>Number(localStorage.getItem('skyBest')||0)),[y,setY]=useState(55),[obs,setObs]=useState(100);const ref=useRef<number>();useEffect(()=>{if(!playing)return;ref.current=window.setInterval(()=>{setScore(s=>s+1);setObs(o=>{const n=o-3;if(n<0){setPlaying(false);return 100}return n});setY(v=>Math.max(8,Math.min(82,v+(Math.random()>.5?2:-2))))},120);return()=>clearInterval(ref.current)},[playing]);return <div className="miniGame"><div className="gameHud"><b>✈ SKY FLIGHT</b><span>Toque ou pressione ESPAÇO para subir</span></div><div className="flightArena" onClick={()=>setY(v=>Math.max(8,v-9))} onKeyDown={e=>e.code==='Space'&&setY(v=>Math.max(8,v-9))} tabIndex={0}><div className="plane" style={{top:y+'%'}}>✈</div><div className="obstacle" style={{left:obs+'%'}}>▮</div>{!playing&&<div className="gameOver">FIM DE PARTIDA<small>Você fez {score} pontos</small></div>}</div><ScoreBar score={score} best={best} playing={playing} onRestart={()=>{setScore(0);setObs(100);setY(55);setPlaying(true);if(score>best){setBest(score);localStorage.setItem('skyBest',String(score))}}}/></div>}
function TigerQuest(){const[playing,setPlaying]=useState(true),[score,setScore]=useState(0),[best,setBest]=useState(()=>Number(localStorage.getItem('tigerBest')||0)),[pos,setPos]=useState(50),[star,setStar]=useState({x:75,y:50});useEffect(()=>{if(!playing)return;const h=setInterval(()=>{setStar(s=>({x:10+Math.random()*80,y:15+Math.random()*70}))},1300);return()=>clearInterval(h)},[playing]);const move=(dx:number,dy:number)=>{setPos(p=>Math.max(5,Math.min(95,p+dx)))};const collect=()=>{setScore(s=>s+10);setStar({x:10+Math.random()*80,y:15+Math.random()*70})};return <div className="miniGame"><div className="gameHud"><b>🐯 TIGER QUEST</b><span>Toque nas estrelas • use A/D no teclado</span></div><div className="tigerArena" onClick={collect}><div className="tiger" style={{left:pos+'%'}}>🐯</div><button className="starTarget" style={{left:star.x+'%',top:star.y+'%'}} onClick={e=>{e.stopPropagation();collect()}}>★</button>{!playing&&<div className="gameOver">FIM DE PARTIDA</div>}</div><div className="touchControls"><button onClick={()=>move(-8,0)}>←</button><ScoreBar score={score} best={best} playing={playing} onRestart={()=>{if(score>best){setBest(score);localStorage.setItem('tigerBest',String(score))};setScore(0);setPlaying(true)}}/><button onClick={()=>move(8,0)}>→</button></div></div>}
function Hoops(){const[playing,setPlaying]=useState(true),[score,setScore]=useState(0),[time,setTime]=useState(30),[best,setBest]=useState(()=>Number(localStorage.getItem('hoopsBest')||0)),[power,setPower]=useState(50);useEffect(()=>{if(!playing)return;const h=setInterval(()=>setTime(t=>{if(t<=1){setPlaying(false);return 0}return t-1}),1000);return()=>clearInterval(h)},[playing]);const shoot=()=>{if(!playing)return;const made=Math.abs(power-55)<20;if(made)setScore(s=>s+2);setPower(10+Math.random()*80)};return <div className="miniGame"><div className="gameHud"><b>🏀 HOOPS CHALLENGE</b><span>30 segundos • acerte o aro</span></div><div className="hoopsArena" onClick={shoot}><div className="hoop">🏀<span>╭━━╮</span></div><div className="shotPower" style={{width:power+'%'}}/><div className="timer">{time}s</div>{!playing&&<div className="gameOver">TEMPO!<small>{score} pontos</small></div>}</div><div className="scoreBar"><div><span>PONTOS</span><b>{score}</b></div><div><span>RECORDE</span><b>{best}</b></div>{!playing&&<button className="restart" onClick={()=>{if(score>best){setBest(score);localStorage.setItem('hoopsBest',String(score))};setScore(0);setTime(30);setPlaying(true)}}><RotateCcw size={16}/> Jogar novamente</button>}</div></div>}
function CardMasters(){const symbols=['♠','♥','♦','♣','★','♜','✦','◆'];const shuffled=()=>[...symbols,...symbols].map((s,i)=>({id:i,symbol:s,flipped:false,matched:false})).sort(()=>Math.random()-.5);const[cards,setCards]=useState(shuffled);const[open,setOpen]=useState<number[]>([]);const[moves,setMoves]=useState(0);const[best,setBest]=useState(()=>Number(localStorage.getItem('cardBest')||0));const[locked,setLocked]=useState(false);const matchedCount=cards.filter(c=>c.matched).length;const won=matchedCount===cards.length;useEffect(()=>{if(won&&moves>0){if(best===0||moves<best){setBest(moves);localStorage.setItem('cardBest',String(moves))}}},[won]);const flip=(id:number)=>{if(locked)return;const card=cards.find(c=>c.id===id);if(!card||card.flipped||card.matched)return;const nextOpen=[...open,id];setCards(cs=>cs.map(c=>c.id===id?{...c,flipped:true}:c));if(nextOpen.length<2){setOpen(nextOpen);return}setLocked(true);setMoves(m=>m+1);const[a,b]=nextOpen;const ca=cards.find(c=>c.id===a),cb=card;if(ca&&cb.symbol===ca.symbol){setTimeout(()=>{setCards(cs=>cs.map(c=>c.id===a||c.id===id?{...c,matched:true}:c));setOpen([]);setLocked(false)},450)}else{setTimeout(()=>{setCards(cs=>cs.map(c=>c.id===a||c.id===id?{...c,flipped:false}:c));setOpen([]);setLocked(false)},700)}};const restart=()=>{setCards(shuffled());setOpen([]);setMoves(0);setLocked(false)};return <div className="miniGame"><div className="gameHud"><b>🃏 CARD MASTERS</b><span>Encontre os pares com o menor número de jogadas</span></div><div className="cardArena"><div className="memHud"><span>JOGADAS<b>{moves}</b></span><span>PARES<b>{matchedCount/2}/{symbols.length}</b></span><span>RECORDE<b>{best||'-'}</b></span></div><div className="cardGrid">{cards.map(c=><div key={c.id} className={'memCard'+(c.flipped||c.matched?' flipped':'')+(c.matched?' matched':'')} onClick={()=>flip(c.id)}><div className="memFace back">?</div><div className="memFace front">{c.symbol}</div></div>)}</div>{won&&<div className="gameOver">VOCÊ VENCEU!<small>{moves} jogadas</small></div>}</div><div className="scoreBar"><div><span>JOGADAS</span><b>{moves}</b></div><div><span>RECORDE</span><b>{best||'-'}</b></div><button className="restart" onClick={restart}><RotateCcw size={16}/> Jogar novamente</button></div></div>}

function CardDuel(){const ranks=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];const suits=[{s:'♠',c:'black'},{s:'♣',c:'black'},{s:'♥',c:'red'},{s:'♦',c:'red'}];const draw=()=>{const rank=ranks[Math.floor(Math.random()*ranks.length)];const suit=suits[Math.floor(Math.random()*suits.length)];return{rank,value:ranks.indexOf(rank),suit:suit.s,color:suit.c}};const[current,setCurrent]=useState(draw);const[next,setNext]=useState<ReturnType<typeof draw>|null>(null);const[streak,setStreak]=useState(0);const[best,setBest]=useState(()=>Number(localStorage.getItem('duelBest')||0));const[over,setOver]=useState(false);const[revealing,setRevealing]=useState(false);const guess=(dir:'higher'|'lower')=>{if(revealing||over)return;const card=draw();setRevealing(true);setNext(card);setTimeout(()=>{const correct=dir==='higher'?card.value>=current.value:card.value<=current.value;if(correct){const s=streak+1;setStreak(s);if(s>best){setBest(s);localStorage.setItem('duelBest',String(s))}setCurrent(card);setNext(null);setRevealing(false)}else{setOver(true);setRevealing(false)}},550)};const restart=()=>{setCurrent(draw());setNext(null);setStreak(0);setOver(false);setRevealing(false)};return <div className="miniGame"><div className="gameHud"><b>🃑 CARD DUEL</b><span>A próxima carta é maior ou menor?</span></div><div className="duelArena"><div className="streak">SEQUÊNCIA<b>{streak}</b></div><div className="duelRow"><div className={'playCard '+current.color}>{current.suit}<span>{current.rank}</span></div><div className="duelVs">VS</div><div className={'playCard '+(next?next.color:'')}>{next?next.suit:'?'}<span>{next?next.rank:''}</span></div></div>{!over?<div className="duelBtns"><button onClick={()=>guess('lower')}>▼ Menor</button><button onClick={()=>guess('higher')}>▲ Maior</button></div>:<div className="gameOver" style={{position:'static',background:'none'}}>FIM DA SEQUÊNCIA<small>Você acertou {streak} vezes seguidas</small></div>}</div><div className="scoreBar"><div><span>SEQUÊNCIA</span><b>{streak}</b></div><div><span>RECORDE</span><b>{best}</b></div>{over&&<button className="restart" onClick={restart}><RotateCcw size={16}/> Jogar novamente</button>}</div></div>}

function evaluatePokerHand(cards:{rank:number;label:string;suit:string;color:string}[]){const values=cards.map(c=>c.rank).sort((a,b)=>a-b);const isFlush=cards.every(c=>c.suit===cards[0].suit);const uniqueVals=[...new Set(values)];let isStraight=false;if(uniqueVals.length===5){if(uniqueVals[4]-uniqueVals[0]===4)isStraight=true;if(uniqueVals.join(',')==='2,3,4,5,14')isStraight=true}const countsMap:Record<number,number>={};values.forEach(v=>countsMap[v]=(countsMap[v]||0)+1);const countsArr=Object.entries(countsMap).map(([val,cnt])=>({val:Number(val),cnt})).sort((a,b)=>b.cnt-a.cnt||b.val-a.val);const isRoyal=isStraight&&isFlush&&uniqueVals[0]===10;if(isRoyal)return{name:'Royal Flush',points:800};if(isStraight&&isFlush)return{name:'Straight Flush',points:250};if(countsArr[0].cnt===4)return{name:'Quadra',points:125};if(countsArr[0].cnt===3&&countsArr[1]?.cnt===2)return{name:'Full House',points:45};if(isFlush)return{name:'Flush',points:30};if(isStraight)return{name:'Sequência',points:20};if(countsArr[0].cnt===3)return{name:'Trinca',points:15};if(countsArr[0].cnt===2&&countsArr[1]?.cnt===2)return{name:'Dois Pares',points:10};if(countsArr[0].cnt===2&&countsArr[0].val>=11)return{name:'Par de Valetes ou Mais',points:5};return{name:'Sem combinação',points:0}}
function PokerDraw(){const RANK_LABELS=['2','3','4','5','6','7','8','9','10','J','Q','K','A'];const SUITS=[{s:'♠',c:'black'},{s:'♣',c:'black'},{s:'♥',c:'red'},{s:'♦',c:'red'}];const freshDeck=()=>{const d:{rank:number;label:string;suit:string;color:string}[]=[];SUITS.forEach(su=>RANK_LABELS.forEach((l,i)=>d.push({rank:i+2,label:l,suit:su.s,color:su.c})));return d.sort(()=>Math.random()-.5)};const[state,setState]=useState(()=>{const d=freshDeck();return{hand:d.slice(0,5),pool:d.slice(5)}});const[held,setHeld]=useState([false,false,false,false,false]);const[stage,setStage]=useState<'select'|'result'>('select');const[result,setResult]=useState<{name:string;points:number}|null>(null);const[score,setScore]=useState(0);const[best,setBest]=useState(()=>Number(localStorage.getItem('pokerBest')||0));const toggleHold=(i:number)=>{if(stage!=='select')return;setHeld(h=>h.map((v,idx)=>idx===i?!v:v))};const drawCards=()=>{if(stage!=='select')return;const newHand=[...state.hand];const newPool=[...state.pool];for(let i=0;i<5;i++){if(!held[i]){const c=newPool.shift();if(c)newHand[i]=c}}const evalRes=evaluatePokerHand(newHand);setState({hand:newHand,pool:newPool});setResult(evalRes);setScore(s=>s+evalRes.points);if(evalRes.points>best){setBest(evalRes.points);localStorage.setItem('pokerBest',String(evalRes.points))}setStage('result')};const newHand=()=>{const d=freshDeck();setState({hand:d.slice(0,5),pool:d.slice(5)});setHeld([false,false,false,false,false]);setStage('select');setResult(null)};return <div className="miniGame"><div className="gameHud"><b>🂡 POKER · JACKS OR BETTER</b><span>Segure as cartas boas e compre pra montar a melhor mão</span></div><div className="pokerArena"><div className="streak">PONTOS<b>{score}</b></div><div className="pokerHand">{state.hand.map((c,i)=><div key={i} className={'pokerCard '+c.color+(held[i]?' held':'')} onClick={()=>toggleHold(i)}>{c.label}<span>{c.suit}</span>{held[i]&&<em>SEGURAR</em>}</div>)}</div>{stage==='result'&&result&&<div className="pokerResult">{result.name}{result.points>0?' · +'+result.points+' pts':''}</div>}{stage==='select'?<button className="primary" onClick={drawCards}><Play size={16} fill="currentColor"/> Comprar cartas</button>:<button className="restart" onClick={newHand}><RotateCcw size={16}/> Nova mão</button>}</div><div className="scoreBar"><div><span>PONTOS</span><b>{score}</b></div><div><span>RECORDE</span><b>{best}</b></div></div></div>}

function DemoGame({game}:{game:Game}){return <div className="miniGame"><div className="gameHud"><b>{game.icon} {game.title}</b><span>Modo demonstração</span></div><div className="demoArena"><div>{game.icon}</div><button className="primary"><Play size={17} fill="currentColor"/> Iniciar</button></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);